POST http://localhost:5000/api/v1/sensor/
Content-Type: application/json

{
    "sensor_name": "Sensor 2",
    "sensor_type": "Smoke",
    "fire_level": 0,
    "smoke_value": 700,
    "location": "Warehouse 2"
}
