POST http://localhost:5000/api/v1/sensor/
Content-Type: application/json

{
    "sensor_name": "Sensor 1",
    "sensor_type": "api",
    "fire_level": 0,
    "smoke_value": 1,
    "location": "Warehouse 2"
}

###
GET http://localhost:5000/api/v1/sensor/
Content-Type: application/json

{

}
