POST http://localhost:5000/api/v1/users/
Content-Type: application/json

{
    "email": "dimas@user.com",
    "password": "dimas",
    "confirmPassword": "dimas",
    "role": "user"
}



###
GET http://localhost:5000/api/v1/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTcxMjE5MTUxNywiZXhwIjoxNzEyMTkxNTM3fQ.hohIkCLJaexkH-ml35mWIBiLv_d2dDm5u0SfPOjkxFY
 



 
###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
    "email": "dimas@user.com",
    "password": "dimas"
}