POST http://localhost:5000/api/v1/users/
Content-Type: application/json

{
    "nama": "firefighter",
    "email": "firefighter@firefighter.com",
    "password": "firefighter",
    "confirmPassword": "firefighter",
    "role": "firefighter",
    
}



###
GET http://localhost:5000/api/v1/users/
Authorization: Bearerey eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMzgzODA1MiwiZXhwIjoxNzEzODM5MDUyfQ.lYW8CiEyMZ5TQeFc1ESLnPePWHRYfEaJyJA9a1yEZF8
 
###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
    "email": "wendy@admin.com",
    "password": "dimas123"
}

###
PUT http://localhost:5000/api/v1/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMzQyOTM5NCwiZXhwIjoxNzEzNDMwMzk0fQ.50YyqkXe56MRIYx51uRntpJJNgeYT3KAOpAJMwU6Bps
Content-Type: application/json

{
    "oldPassword": "wendy",
    "newPassword": "dimas123",
    "confirmPassword": "dimas123"
}


###
DELETE http://localhost:5000/api/v1/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMzkyMDg0NCwiZXhwIjoxNzEzOTIxODQ0fQ._oLwAjMV_AcKsCWU3gZKP8lVbJfU20BvjPFOfX4E_5g

###
POST http://localhost:5000/api/v1/sos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxNDAwNzU5NSwiZXhwIjoxNzE0MDA4NTk1fQ.1ycfmSQ8CkTIlsZpqJ3nZ2g081CRfdwjwGdCjXvEQz0
Content-Type: application/json

 {
  "firefighterId": 8,
  "message": "Emergency SOS Boys"
}

###
GET http://localhost:5000/api/v1/user/notification/3
Content-Type: application/json

{

}